apiVersion: v1
kind: Pod
metadata:
  name: pod3
  metadata:
    labels:
      custom.sched.io/pod/restrictions: "10" # Max cost + SLA Required
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80