kind: Node
apiVersion: v1
metadata:
  name: node1
  labels:
    custom.sched.io/node/trust-vector: "1,0.6,4,2" # [uptime, SLA Compliance level (Karma), Cost/cpu, cost / memoria]
status:
  capacity:
    cpu: '4'
    memory: 32Gi
    pods: '110'
  allocatable:
    cpu: '4'
    memory: 32Gi
    pods: '110'
