kind: Node
apiVersion: v1
metadata:
  name: node3
  annotations:
    # kontext.io/uptime: custom-type-1 # Obtain from the v1.Node Uptime metric (K8s API)
    kontext.io/karma: "0.90" # Higher karma indicates better reliability + 
    kontext.io/cost-by-cpu: "0.5" # Cost per CPU unit (Total Fake)
    kontext.io/cost-by-memory: "0.2" # Cost per GB of Memory (Total Fake)
status:
  capacity:
    cpu: 4
    memory: 32Gi
    pods: 110
  allocatable:
    cpu: 4
    memory: 32Gi
    pods: 110